### ISSUE TITLE
Some heartless don't give heart's

### ISSUE THREAD

**Issue by kirbykiddd** [Wehavecookies56/Kingdom-Keys#15]
These ones to be specific. Shadow, GigaShadow, MegaShadow, Darkball, Shadow Glob

**Comment by PungentZeus0** [comment]
**This detail is most likely intentional.** Those specific Heartless do not give Heart Points/Hearts when killed in Kingdom Keys in order to remain faithful to how they work in the source material.

Or, an optionally more nerdy lore explanation from the official Kingdom Hearts series itself: 
The Heartless you mentioned are classed as natural Heartless, or Purebloods. The Pureblood class does not bear hearts the same way the other class of Heartless, the Emblems, do; this is due to the differing facets of how Heartless of either class are created. Thus, when a Pureblood Heartless is killed in-world, it does not release a heart as there is none to release. This detail was fully addressed in _Kingdom Hearts: 358/2 Days_, and if you wish to know more from the source material, I would recommend you take a look at [the main page for Heartless on KHWiki](https://www.khwiki.com/Heartless).

**Comment by Abelatox** [comment]
Exactly just like @PungentZeus0 mentioned, that detail is intentional since they are pureblood and if you check on the games you'll notice that kind of heartless do not release a heart.
