### ISSUE TITLE
Game Crash when i die 

### ISSUE THREAD

**Issue by NeoForge** [Wehavecookies56/Kingdom-Keys#40]
I added the mod to ATM8 to play on a server with my friend however when i die the game crash (not the server) , 
you can see the error in the log file.

[2023-09-23-4.log](https://github.com/Wehavecookies56/Kingdom-Keys/files/12707260/2023-09-23-4.log)

**Comment by P3rf3ctXZer0** [comment]
I can attest this is an issue. https://gist.github.com/P3rf3ctXZer0/c969f3218194a8a4bb01b4822757d35f

This seems to be the offending line
``[03.10 23:38:23] [Server] java.lang.NullPointerExceptionCannot invoke "online.kingdomkeys.kingdomkeys.capability.IPlayerCapabilities.getNumberOfAbilitiesEquipped(String)" because "playerData" is null``
